# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbb75319dc7f7249fa7708ea27e74e594213237dad04d35b0a232fdd4c9bf0385a11a454003d6af6c30be622c6a67b9c183a9f87f7fa01ff63d9493c41be5772

test:
  secret_key_base: b7d08ef6c4a45e011f0d25487b805319376befa93289780ae3b611736594a32ec6f2d415909baa2c7629f07dc5fd5d2f078dc4977e44f5516b66f591759b3a56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
